import { Dimensions, StyleSheet, Platform } from 'react-native';
const { width } = Dimensions.get('window');
const CARD_WIDTH = (width - 44) / 2;

// ─── Teal + Coral Color Palette ────────────────────────────────────────────
const C = {
  bg:           '#F8FAFC',
  surface:      '#FFFFFF',
  elev:         '#F1F5F9',
  border:       '#E2E8F0',
  t1:           '#0F172A',
  t2:           '#475569',
  t3:           '#94A3B8',
  brand:        '#0D9488',
  brandL:       '#14B8A6',
  brandD:       '#0F766E',
  brandBg:      '#F0FDFA',
  brandBorder:  '#99F6E4',
  accent:       '#F97316',
  accentL:      '#FB923C',
  accentBg:     '#FFF7ED',
  accentBorder: '#FED7AA',
  success:      '#059669',
  successBg:    '#ECFDF5',
  successBorder:'#A7F3D0',
  danger:       '#DC2626',
  dangerBg:     '#FEF2F2',
  dangerBorder: '#FECACA',
  info:         '#0284C7',
  infoBg:       '#F0F9FF',
  infoBorder:   '#BAE6FD',
  white:        '#FFFFFF',
  black:        '#000000',
};

export const Colors = C;
export const CARD_WIDTH_EXPORT = CARD_WIDTH;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  listContent: { paddingBottom: 20 },
  row: { justifyContent: 'space-between', paddingHorizontal: 12, marginBottom: 2 },

  heroWrap: { height: 250, overflow: 'hidden', backgroundColor: C.brandD },
  heroImage: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  heroScrimTop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.22)' },
  heroScrimBottom: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 130, backgroundColor: 'rgba(0,0,0,0.48)' },
  heroNav: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingBottom: 10 },
  heroIconBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(0,0,0,0.3)', justifyContent: 'center', alignItems: 'center' },
  heroTitleWrap: { flex: 1, alignItems: 'center' },
  heroTitle: { fontSize: 19, fontWeight: '800', color: '#fff', letterSpacing: 0.2, textTransform: 'capitalize', textShadowColor: 'rgba(0,0,0,0.3)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 4 },
  heroCount: { fontSize: 12, color: 'rgba(255,255,255,0.75)', marginTop: 2, fontWeight: '500' },

  // ── Search bar — persistent (no more expand/collapse), same language as
  // the Products screen search bar: teal focus ring, clear (x) + go (arrow).
  heroSearchWrap: { position: 'absolute', bottom: 18, left: 16, right: 16, zIndex: 5 },
  heroSearchBar: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: C.white, borderRadius: 14,
    height: 48,
    borderWidth: 2, borderColor: 'transparent',
    shadowColor: C.black, shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1, shadowRadius: 10, elevation: 6,
  },
  heroSearchBarFocused: {
    borderColor: C.brand,
    shadowOpacity: 0.16,
  },
  heroSearchInput: { flex: 1, fontSize: 14, color: C.t1, paddingHorizontal: 10, height: '100%' },
  searchGoBtn: {
    width: 30, height: 30, borderRadius: 15,
    backgroundColor: C.brand, justifyContent: 'center', alignItems: 'center',
    marginRight: 8, marginLeft: 2,
  },

  liveDropdown: {
    position: 'absolute', top: '100%', left: 0, right: 0, marginTop: 8,
    backgroundColor: C.white, borderRadius: 14,
    shadowColor: C.black, shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15, shadowRadius: 14, elevation: 10, overflow: 'hidden',
  },
  liveRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 14, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F5F5F5' },
  liveThumb: { width: 42, height: 42, borderRadius: 10, backgroundColor: '#F5F5F5' },
  liveRowName: { fontSize: 13.5, fontWeight: '600', color: C.t1 },
  liveRowPrice: { fontSize: 12.5, fontWeight: '800', color: C.accent },
  liveRowLocation: { fontSize: 11, color: C.t3 },
  liveViewAll: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 12, backgroundColor: C.brandBg },
  liveViewAllText: { fontSize: 12.5, fontWeight: '700', color: C.brand },
  liveEmptyText: { fontSize: 12.5, color: C.t3, marginTop: 6 },

  recentWrap: { backgroundColor: C.white, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: '#F0F0F0' },
  recentHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  recentTitle: { fontSize: 12, color: C.t3, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6 },
  recentClear: { fontSize: 12, color: C.danger, fontWeight: '600' },
  recentChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.brandBg, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 20, borderWidth: 1, borderColor: C.brandBorder, gap: 5 },
  recentChipText: { fontSize: 13, color: C.brand, fontWeight: '600' },

  subcatStripWrap: { backgroundColor: C.white, borderBottomWidth: 1, borderBottomColor: '#F0F0F0' },
  subcatStrip: { paddingHorizontal: 12, paddingVertical: 10, gap: 8 },
  subcatPill: { paddingHorizontal: 14, paddingVertical: 7, borderRadius: 20, borderWidth: 1.5, borderColor: '#E0E0E0', backgroundColor: C.white },
  subcatPillActive: { backgroundColor: C.brand, borderColor: C.brand },
  subcatPillText: { fontSize: 13, fontWeight: '600', color: '#555' },
  subcatPillTextActive: { color: '#fff' },

  // ── Results meta row ─────────────────────────────────────────────────────
  resultsMetaRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    backgroundColor: C.white, paddingHorizontal: 14, paddingVertical: 10,
  },
  resultsMetaLeft: { flexDirection: 'row', alignItems: 'center', gap: 8, flex: 1 },
  toolbarCount: { fontSize: 13, color: C.t3, fontWeight: '500' },
  toolbarCountBold: { fontWeight: '800', color: C.t1 },
  searchActiveTag: {
    flexDirection: 'row', alignItems: 'center', gap: 5,
    backgroundColor: C.infoBg, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8,
    maxWidth: 140,
  },
  searchActiveTagText: { fontSize: 11, color: C.info, fontWeight: '600' },

  // ── Sort / Filter bar — same full-width two-segment layout as the
  // Products screen, instead of small floating pill buttons.
  sortFilterBar: {
    flexDirection: 'row', alignItems: 'stretch',
    backgroundColor: C.white,
    borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#EEF1F4',
  },
  sortFilterSegment: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 7, paddingVertical: 13,
  },
  sortFilterSegmentActive: { backgroundColor: C.brandBg },
  sortFilterDivider: { width: 1, backgroundColor: '#EEF1F4', marginVertical: 8 },
  sortFilterText: { fontSize: 13, fontWeight: '700', color: C.t1 },
  sortFilterTextActive: { color: C.brandD },
  filterCountBadge: {
    backgroundColor: C.danger, borderRadius: 8, minWidth: 16, height: 16,
    justifyContent: 'center', alignItems: 'center', paddingHorizontal: 3, marginLeft: 1,
  },
  filterCountBadgeText: { color: '#fff', fontSize: 9, fontWeight: '800' },

  activeFiltersRow: { paddingHorizontal: 14, paddingVertical: 8, gap: 8, backgroundColor: C.bg, flexDirection: 'row', alignItems: 'center' },
  activePill: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: C.infoBg, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1, borderColor: C.infoBorder },
  activePillText: { fontSize: 12, fontWeight: '600', color: C.info },
  clearAllPill: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1, borderColor: C.dangerBorder, backgroundColor: C.dangerBg },
  clearAllPillText: { fontSize: 12, fontWeight: '600', color: C.danger },

  searchResultBanner: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.brandBg, paddingHorizontal: 14, paddingVertical: 10, gap: 7, borderBottomWidth: 1, borderBottomColor: C.brandBorder },
  searchResultText: { flex: 1, fontSize: 13, color: '#555', fontWeight: '500' },
  searchResultQuery: { color: C.brand, fontWeight: '700' },

  card: { width: CARD_WIDTH, backgroundColor: C.white, borderRadius: 18, overflow: 'hidden', marginBottom: 12, marginTop: 6, shadowColor: C.black, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 4 },
  cardImageWrap: { height: 148, position: 'relative', backgroundColor: '#F5F5F5' },
  cardImage: { width: '100%', height: '100%' },
  conditionBadge: { position: 'absolute', top: 8, left: 8, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  conditionBadgeText: { fontSize: 10, fontWeight: '700' },
  oosOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  oosText: { color: '#fff', fontSize: 13, fontWeight: '800', letterSpacing: 0.4 },
  lowStockBadge: { position: 'absolute', bottom: 8, left: 8, flexDirection: 'row', alignItems: 'center', backgroundColor: C.danger, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 8, gap: 3 },
  lowStockText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  negotiableTag: { position: 'absolute', top: 8, right: 8, backgroundColor: C.accent, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 8 },
  negotiableTagText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  imageCountBadge: { position: 'absolute', bottom: 8, right: 8, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)', paddingHorizontal: 6, paddingVertical: 3, borderRadius: 8, gap: 3 },
  imageCountText: { color: '#fff', fontSize: 10, fontWeight: '600' },

  cardAddBtn: {
    width: 34, height: 34, borderRadius: 17,
    backgroundColor: C.brand,
    justifyContent: 'center', alignItems: 'center',
    shadowColor: C.brandD, shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3, shadowRadius: 6, elevation: 4,
    marginLeft: 8,
  },
  cardAddBtnDisabled: { backgroundColor: '#BDBDBD', shadowOpacity: 0 },
  cardQtyPill: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#fff', borderRadius: 17,
    paddingHorizontal: 2, height: 34,
    borderWidth: 1.5, borderColor: C.brandBorder,
    marginLeft: 8,
  },
  cardQtyBtn: { width: 26, height: 26, borderRadius: 13, justifyContent: 'center', alignItems: 'center' },
  cardQtyNum: { minWidth: 22, textAlign: 'center', fontSize: 13, fontWeight: '800', color: C.brand, paddingHorizontal: 2 },

  cardBody: { padding: 12, paddingTop: 10 },
  cardName: { fontSize: 13, fontWeight: '700', color: C.t1, lineHeight: 18, minHeight: 36, marginBottom: 4 },
  cardLocationRow: { flexDirection: 'row', alignItems: 'center', gap: 3, marginBottom: 6 },
  cardLocation: { fontSize: 11, color: C.t3, flex: 1 },
  cardFooter: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
  cardPrice: { fontSize: 16, fontWeight: '800', color: C.accent },
  cardVendor: { fontSize: 10, color: C.t3, marginTop: 1 },
  cardPriceSection: { flex: 1, minWidth: 0 },
  cardPriceStack: { gap: 3 },
  cardPriceRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  cardOriginalPrice: { fontSize: 11, color: C.t3, fontWeight: '600', textDecorationLine: 'line-through' },
  cardDiscountPill: { backgroundColor: C.dangerBg, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, borderWidth: 1, borderColor: C.dangerBorder },
  cardDiscountPillText: { fontSize: 9, fontWeight: '800', color: C.danger },
  cardSavingsText: { fontSize: 10, color: C.success, fontWeight: '700' },
  cardRatingRow: { flexDirection: 'row', alignItems: 'center', gap: 2, marginTop: 4 },
  cardRatingText: { fontSize: 11, color: C.t2, fontWeight: '600' },

  loadMoreWrap: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 10, paddingVertical: 20 },
  loadMoreText: { fontSize: 13, color: C.t3, fontWeight: '500' },
  endOfListWrap: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 24, paddingVertical: 28, gap: 12 },
  endOfListLine: { flex: 1, height: 1, backgroundColor: '#E0E0E0' },
  endOfListText: { fontSize: 12, color: C.t3, fontWeight: '500' },

  emptyWrap: { alignItems: 'center', paddingVertical: 64, paddingHorizontal: 40 },
  emptyIconBg: { width: 88, height: 88, borderRadius: 44, backgroundColor: C.brandBg, justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
  emptyTitle: { fontSize: 20, fontWeight: '800', color: C.brand, marginBottom: 8 },
  emptySubtitle: { fontSize: 14, color: C.t3, textAlign: 'center', lineHeight: 22, marginBottom: 28 },
  emptyBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.brand, paddingHorizontal: 22, paddingVertical: 12, borderRadius: 12, gap: 8, shadowColor: C.brand, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 6, elevation: 4 },
  emptyBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },

  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)' },
  bottomSheet: { backgroundColor: C.white, borderTopLeftRadius: 26, borderTopRightRadius: 26, paddingHorizontal: 20, paddingTop: 12, shadowColor: C.black, shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.08, shadowRadius: 12, elevation: 16 },
  sheetHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#E0E0E0', alignSelf: 'center', marginBottom: 18 },
  sheetTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  sheetTitle: { fontSize: 18, fontWeight: '800', color: C.brand },
  sheetClearBtn: { fontSize: 14, color: C.danger, fontWeight: '600' },
  sheetSubHeading: { fontSize: 12, color: C.t3, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6, marginBottom: 12, marginTop: 6 },
  sheetRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, paddingHorizontal: 12, borderRadius: 12, marginBottom: 6, gap: 12 },
  sheetRowActive: { backgroundColor: C.brandBg },
  sheetRowIcon: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#F5F5F5', justifyContent: 'center', alignItems: 'center' },
  sheetRowIconActive: { backgroundColor: C.brand },
  sheetRowText: { flex: 1, fontSize: 15, color: '#333', fontWeight: '500' },
  sheetRowTextActive: { color: C.brand, fontWeight: '700' },
  filterSectionLabel: { fontSize: 12, color: C.t3, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6, marginBottom: 12 },
  filterChipsWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 4 },
  filterChip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, borderWidth: 1.5, borderColor: '#E0E0E0', backgroundColor: C.white },
  filterChipActive: { backgroundColor: C.brand, borderColor: C.brand },
  filterChipText: { fontSize: 13, fontWeight: '600', color: '#555' },
  filterChipTextActive: { color: '#fff' },

  // ── Price range + negotiable toggle (added filters) ─────────────────────
  priceRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 4 },
  priceInputWrap: { flex: 1 },
  priceInputLabel: { fontSize: 11, color: C.t3, fontWeight: '600', marginBottom: 5 },
  priceInput: {
    backgroundColor: '#F5F5F5', borderRadius: 10, paddingHorizontal: 12,
    paddingVertical: 10, fontSize: 14, color: C.t1,
    borderWidth: 1, borderColor: '#E0E0E0',
  },
  priceDash: { width: 16, height: 2, backgroundColor: C.t3, marginTop: 18 },
  toggleRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingVertical: 14, borderTopWidth: 0.5, borderTopColor: '#F0F0F0', marginTop: 16,
  },
  toggleRowLabel: { fontSize: 14, fontWeight: '700', color: C.t1 },
  toggleRowSub: { fontSize: 11, color: C.t3, marginTop: 2 },
  toggleSwitch: {
    width: 44, height: 26, borderRadius: 13,
    backgroundColor: '#E0E0E0', justifyContent: 'center', padding: 3,
  },
  toggleSwitchOn: { backgroundColor: C.brand },
  toggleThumb: {
    width: 20, height: 20, borderRadius: 10,
    backgroundColor: C.white,
    shadowColor: C.black, shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15, shadowRadius: 2, elevation: 2,
  },
  toggleThumbOn: { transform: [{ translateX: 18 }] },

  applyBtn: { backgroundColor: C.brand, borderRadius: 14, paddingVertical: 16, alignItems: 'center', marginTop: 20, marginBottom: 4, flexDirection: 'row', justifyContent: 'center', gap: 8, shadowColor: C.brand, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 8, elevation: 4 },
  applyBtnText: { color: '#fff', fontSize: 15, fontWeight: '800' },

  toastWrap: { position: 'absolute', top: 0, left: 0, right: 0, zIndex: 999, alignItems: 'center', paddingTop: Platform.OS === 'ios' ? 54 : 40, pointerEvents: 'none' },
  toast: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.brandD, paddingHorizontal: 18, paddingVertical: 12, borderRadius: 30, gap: 10, shadowColor: C.black, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 8, elevation: 8, maxWidth: width - 60 },
  toastText: { fontSize: 13, color: 'rgba(255,255,255,0.92)', flex: 1 },
  discountBadge: { position: 'absolute', top: 8, left: 8, backgroundColor: C.danger, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, flexDirection: 'row', alignItems: 'center', gap: 4, zIndex: 3 },
  discountBadgeText: { color: '#FFFFFF', fontSize: 10, fontWeight: '800', letterSpacing: 0.3 },
});