import {
  View, Text, ScrollView, StyleSheet, TouchableOpacity, Image,
  RefreshControl, ActivityIndicator, Dimensions, Alert, Modal,
  TextInput, StatusBar, TouchableWithoutFeedback, FlatList,
} from 'react-native';
const { width } = Dimensions.get('window');

// ─── Teal + Coral Palette ──────────────────────────────────────────────────
const C = {
  bg:           '#F8FAFC',
  surface:      '#FFFFFF',
  elev:         '#F1F5F9',
  t1:           '#0F172A',
  t2:           '#475569',
  t3:           '#94A3B8',
  brand:        '#0D9488',
  brandL:       '#14B8A6',
  brandD:       '#0F766E',
  brandBg:      '#F0FDFA',
  brandBorder:  '#99F6E4',
  accent:       '#F97316',
  accentL:      '#FB923C',
  accentBg:     '#FFF7ED',
  accentBorder: '#FED7AA',
  success:      '#059669',
  successBg:    '#ECFDF5',
  successBorder:'#A7F3D0',
  danger:       '#DC2626',
  dangerBg:     '#FEF2F2',
  dangerBorder: '#FECACA',
  info:         '#0284C7',
  infoBg:       '#F0F9FF',
  infoBorder:   '#BAE6FD',
  white:        '#FFFFFF',
  black:        '#000000',
};

// ─────────────────────────────────────────────
// STYLES
// ─────────────────────────────────────────────
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  scrollContent: {},
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: C.bg },
  loadingText: { marginTop: 14, fontSize: 15, color: C.t2 },

  // ── Header ──
  header: {
    backgroundColor: C.surface,
    marginHorizontal: 4,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 18,
    zIndex: 100,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  headerTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14 },
  headerGreeting: { fontSize: 11, color: C.t3, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 3 },
  headerTitle: { fontSize: 20, fontWeight: '800', color: C.t1, letterSpacing: -0.3 },
  locationPill: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: C.elev, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4, alignSelf: 'flex-start', marginTop: 6 },
  locationDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: C.success },
  locationText: { fontSize: 11, color: C.t2, fontWeight: '500' },
  headerActions: { flexDirection: 'row', gap: 6, marginTop: 4 },
  headerIconBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: C.elev, justifyContent: 'center', alignItems: 'center', position: 'relative' },
  notifBadge: { position: 'absolute', top: 3, right: 3, backgroundColor: C.danger, borderRadius: 8, minWidth: 14, height: 14, justifyContent: 'center', alignItems: 'center', borderWidth: 1.5, borderColor: C.surface },
  notifBadgeText: { color: '#fff', fontSize: 8, fontWeight: '800', paddingHorizontal: 2 },

  // ── Search ──
  searchWrapper: { position: 'relative', zIndex: 200 },
  searchBar: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.elev, borderRadius: 14, paddingLeft: 14, paddingRight: 0, paddingVertical: 0 },
  searchInput: { flex: 1, fontSize: 14, color: C.t1, paddingVertical: 12 },
  searchIconBtn: { width: 64, height: 34, backgroundColor: C.brand, justifyContent: 'center', alignItems: 'center', borderTopRightRadius: 14, borderBottomRightRadius: 14, borderTopLeftRadius: 0, borderBottomLeftRadius: 0, shadowColor: C.brand, shadowOffset: { width: -2, height: 0 }, shadowOpacity: 0.15, shadowRadius: 4, elevation: 2 },
  searchBackdrop: { position: 'absolute', top: 0, left: -16, right: -16, bottom: -1200, zIndex: 998 },
  searchDropdown: { position: 'absolute', top: 50, left: 0, right: 0, backgroundColor: C.surface, borderRadius: 14, borderWidth: 1, borderColor: '#E8E8E8', shadowColor: C.black, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.08, shadowRadius: 12, elevation: 10, zIndex: 999, overflow: 'hidden' },
  searchSection: { paddingVertical: 6 },
  searchSectionLabel: { fontSize: 11, fontWeight: '700', color: C.t3, textTransform: 'uppercase', letterSpacing: 0.5, paddingHorizontal: 14, paddingTop: 10, paddingBottom: 4 },
  searchRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 9, gap: 12 },
  searchThumb: { width: 44, height: 44, borderRadius: 10, backgroundColor: C.brandBg },
  searchRowName: { fontSize: 13, fontWeight: '600', color: C.t1 },
  searchRowPrice: { fontSize: 12, fontWeight: '700', color: C.accent },
  searchRowCampus: { fontSize: 10, fontWeight: '600', color: C.brand, backgroundColor: C.brandBg, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  noResults: { alignItems: 'center', padding: 28 },
  noResultsTitle: { fontSize: 15, fontWeight: '600', color: C.t2, marginTop: 10 },
  noResultsSub: { fontSize: 13, color: C.t3, marginTop: 3 },
  viewAllRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 14, borderTopWidth: 0.5, borderTopColor: '#F0F0F0' },
  viewAllText: { fontSize: 13, fontWeight: '600', color: C.brand },

  // ── Carousel ──
  carouselSection: { marginHorizontal: 16, marginTop: 16 },
  carouselWrap: { borderRadius: 20, overflow: 'hidden' },
  slideWrapper: { height: 200, position: 'relative', backgroundColor: C.brandD },
  slideImage: { width: '100%', height: '100%', position: 'absolute' },
  slideScrim: { ...StyleSheet.absoluteFillObject },
  slideContent: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 18 },
  slideTagPill: { alignSelf: 'flex-start', backgroundColor: 'rgba(255,255,255,0.15)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.3)', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4, marginBottom: 8 },
  slideTagText: { fontSize: 11, color: '#fff', fontWeight: '600' },
  slideTitle: { fontSize: 20, fontWeight: '800', color: '#fff', lineHeight: 25, marginBottom: 4, textShadowColor: 'rgba(0,0,0,0.35)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 4 },
  slideSubtitle: { fontSize: 12, color: 'rgba(255,255,255,0.82)', marginBottom: 12 },
  slideBtn: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', borderWidth: 1.5, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 7, gap: 6, backgroundColor: 'rgba(0,0,0,0.22)' },
  slideBtnText: { fontSize: 13, fontWeight: '700', color: '#fff' },
  dotsRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 10, backgroundColor: C.bg, gap: 5 },
  dot: { borderRadius: 4, height: 5 },
  dotActive: { width: 18, backgroundColor: C.brand },
  dotInactive: { width: 5, backgroundColor: C.brandBorder },

  // ── Stats Banner ──
  statsBanner: { flexDirection: 'row', backgroundColor: C.brand, marginHorizontal: 16, marginTop: 10, borderRadius: 14, paddingVertical: 14, paddingHorizontal: 20, justifyContent: 'space-around', alignItems: 'center' },
  statItem: { alignItems: 'center' },
  statValue: { fontSize: 18, fontWeight: '800', color: '#fff' },
  statLabel: { fontSize: 10, color: '#99F6E4', marginTop: 2, fontWeight: '500' },
  statDivider: { width: 1, height: 30, backgroundColor: 'rgba(255,255,255,0.2)' },

  // ── Section ──
  section: { backgroundColor: C.surface, marginTop: 10, paddingTop: 18, paddingBottom: 20 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', paddingHorizontal: 16, marginBottom: 14 },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionTitle: { fontSize: 16, fontWeight: '800', color: C.t1 },
  sectionSubtitle: { fontSize: 12, color: C.t3, marginTop: 2 },
  seeAllRow: { flexDirection: 'row', alignItems: 'center', gap: 2, marginTop: 4 },
  seeAllText: { fontSize: 13, fontWeight: '600', color: C.brand },
  urgentDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.danger, marginTop: 4 },

  // ── Campus cards ──
  campusScrollContent: { paddingHorizontal: 16, gap: 10 },
  campusCard: { width: 140, borderRadius: 16, padding: 13, borderWidth: 1, gap: 7 },
  campusIconBadge: { width: 38, height: 38, borderRadius: 11, justifyContent: 'center', alignItems: 'center' },
  campusIcon: { fontSize: 18 },
  campusName: { fontSize: 13, fontWeight: '700', lineHeight: 17, color: C.t1 },
  campusCountChip: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, borderRadius: 10, paddingHorizontal: 7, paddingVertical: 3, alignSelf: 'flex-start' },
  campusCountDot: { width: 5, height: 5, borderRadius: 3 },
  campusCountText: { fontSize: 10, fontWeight: '700' },
  campusNoListings: { fontSize: 10, color: C.t3 },

  // ── Category ──
  categoryScroll: { paddingHorizontal: 16, gap: 10 },
  categoryPill: { alignItems: 'center', width: 68 },
  categoryIconCircle: { width: 52, height: 52, borderRadius: 26, justifyContent: 'center', alignItems: 'center', marginBottom: 6, borderWidth: 1 },
  categoryEmoji: { fontSize: 22 },
  categoryName: { fontSize: 10, fontWeight: '600', color: C.t2, textAlign: 'center' },

  // ── Product grid ──
  productsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, paddingHorizontal: 16 },
  productCard: { width: (width - 42) / 2, backgroundColor: C.surface, borderRadius: 14, overflow: 'hidden', borderWidth: 1, borderColor: '#F0F0F0', shadowColor: C.black, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.04, shadowRadius: 5, elevation: 2 },
  productImgWrap: { position: 'relative' },
  productImg: { width: '100%', height: 120 },
  productImgPlaceholder: { width: '100%', height: 120, justifyContent: 'center', alignItems: 'center' },
  conditionOverlay: { position: 'absolute', top: 6, left: 6 },
  negotiableTag: { position: 'absolute', top: 6, right: 6, backgroundColor: C.accent, borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
  negotiableTagText: { color: '#fff', fontSize: 9, fontWeight: '700' },
  productBody: { padding: 10 },
  productName: { fontSize: 13, fontWeight: '600', color: C.t1, marginBottom: 4, lineHeight: 17 },
  campusPill: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: C.brandBg, alignSelf: 'flex-start', paddingHorizontal: 7, paddingVertical: 3, borderRadius: 8, marginBottom: 8 },
  campusPillText: { fontSize: 10, fontWeight: '600', color: C.brand },
  productFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  productPrice: { fontSize: 14, fontWeight: '800', color: C.accent },
  addBtn: { width: 28, height: 28, borderRadius: 14, backgroundColor: C.brand, justifyContent: 'center', alignItems: 'center' },
  addBtnActive: { backgroundColor: C.brandD },

  // ── Condition badge ──
  conditionBadge: { paddingHorizontal: 7, paddingVertical: 2, borderRadius: 6, alignSelf: 'flex-start' },
  conditionBadgeText: { fontSize: 9, fontWeight: '700' },

  // ── Deal card (horizontal) ──
  horizontalScroll: { paddingHorizontal: 16, gap: 12 },
  dealCard: { width: 160, height: 200, borderRadius: 16, overflow: 'hidden', backgroundColor: C.brandBg },
  dealImg: { width: '100%', height: '100%', position: 'absolute' },
  dealImgPlaceholder: { width: '100%', height: '100%', justifyContent: 'center', alignItems: 'center' },
  urgentBadge: { position: 'absolute', top: 8, left: 8, flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: C.danger, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 8 },
  urgentBadgeText: { color: '#fff', fontSize: 9, fontWeight: '800' },
  dealOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(0,0,0,0.52)', padding: 12, gap: 5 },
  dealName: { fontSize: 13, fontWeight: '700', color: '#fff' },
  dealBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  dealPrice: { fontSize: 14, fontWeight: '800', color: '#99F6E4' },
  dealNeg: { fontSize: 9, color: '#99F6E4', fontWeight: '600', marginTop: 1 },
  dealAddBtn: { width: 28, height: 28, borderRadius: 9, backgroundColor: C.brand, justifyContent: 'center', alignItems: 'center' },
  dealAddBtnActive: { backgroundColor: C.brandD },

  // ── Sell Banner ──
  bannerSection: { paddingHorizontal: 16, marginTop: 10 },
  sellBanner: { backgroundColor: C.brand, borderRadius: 20, flexDirection: 'row', overflow: 'hidden', minHeight: 150 },
  sellBannerContent: { flex: 1, padding: 18, justifyContent: 'center' },
  sellBannerTag: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: 'rgba(255,255,255,0.18)', alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20, marginBottom: 8 },
  sellBannerTagText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  sellBannerTitle: { fontSize: 22, fontWeight: '800', color: '#fff', marginBottom: 4, lineHeight: 26 },
  sellBannerSub: { fontSize: 12, color: '#99F6E4', marginBottom: 14, lineHeight: 17 },
  sellBannerBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: C.white, alignSelf: 'flex-start', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20 },
  sellBannerBtnText: { fontSize: 13, fontWeight: '700', color: C.brand },
  sellBannerIllustration: { width: 100, justifyContent: 'center', alignItems: 'center' },

  // ── Safety section ──
  safetySection: { backgroundColor: C.surface, marginTop: 10, paddingTop: 18, paddingBottom: 20 },
  safetySectionTitle: { fontSize: 16, fontWeight: '800', color: C.t1, paddingHorizontal: 16, marginBottom: 12 },
  safetyScroll: { paddingHorizontal: 16, gap: 10 },
  safetyCard: { width: 140, backgroundColor: C.successBg, borderRadius: 14, padding: 14, borderWidth: 1, borderColor: C.successBorder, gap: 5 },
  safetyCardIcon: { fontSize: 22 },
  safetyCardTitle: { fontSize: 12, fontWeight: '700', color: C.t1 },
  safetyCardDesc: { fontSize: 11, color: C.t2, lineHeight: 15 },

  // ── Modal ──
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.48)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  successModal: { backgroundColor: C.surface, borderRadius: 24, padding: 30, alignItems: 'center', width: '100%', maxWidth: 340 },
  successTitle: { fontSize: 20, fontWeight: '800', color: C.brand, marginTop: 14, marginBottom: 8 },
  successMessage: { fontSize: 14, color: C.t2, textAlign: 'center', marginBottom: 24, lineHeight: 20 },
  viewCartBtn: { backgroundColor: C.brand, width: '100%', paddingVertical: 14, borderRadius: 14, alignItems: 'center', marginBottom: 10 },
  viewCartBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  continueBtn: { width: '100%', paddingVertical: 14, borderRadius: 14, alignItems: 'center', borderWidth: 1.5, borderColor: C.brandBorder },
  continueBtnText: { color: C.brand, fontSize: 15, fontWeight: '600' },

  // ─── Product Card - Discount styles ───
  discountBadgeProduct: { position: 'absolute', top: 8, left: 8, backgroundColor: C.danger, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 5, zIndex: 3 },
  discountBadgeProductText: { color: '#FFFFFF', fontSize: 10, fontWeight: '800', letterSpacing: 0.3 },
  conditionOverlaySecondary: { position: 'absolute', top: 8, right: 8, zIndex: 3 },
  productPriceStack: { gap: 2 },
  productPriceRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  productOriginalPrice: { fontSize: 10.5, color: C.t3, fontWeight: '600', textDecorationLine: 'line-through' },
  productDiscountPill: { backgroundColor: C.dangerBg, paddingHorizontal: 5, paddingVertical: 1.5, borderRadius: 3, borderWidth: 1, borderColor: C.dangerBorder },
  productDiscountPillText: { fontSize: 8.5, fontWeight: '800', color: C.danger },

  // ─── Deal Card - Discount styles ───
  dealDiscountBadge: { position: 'absolute', top: 8, left: 8, backgroundColor: C.danger, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 5, flexDirection: 'row', alignItems: 'center', gap: 3, zIndex: 3 },
  dealDiscountBadgeText: { color: '#FFFFFF', fontSize: 9, fontWeight: '800', letterSpacing: 0.3 },
  dealPriceStack: { gap: 1 },
  dealPriceRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  dealOriginalPrice: { fontSize: 10, color: C.t3, fontWeight: '600', textDecorationLine: 'line-through' },
  dealDiscountPill: { backgroundColor: C.dangerBg, paddingHorizontal: 5, paddingVertical: 1.5, borderRadius: 3, borderWidth: 1, borderColor: C.dangerBorder },
  dealDiscountPillText: { fontSize: 8, fontWeight: '800', color: C.danger },
});